repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: end-of-file-fixer
        files: \.(proto|txt|sh|rst)$
  - repo: https://github.com/golangci/golangci-lint
    rev: "v1.59.1"
    hooks:
      - id: golangci-lint-full
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.5.7
    hooks:
      - id: ruff
        types_or: [python, pyi, jupyter]
        args: [--fix]
      - id: ruff-format
        types_or: [python, pyi, jupyter]
  - repo: local
    hooks:
      # - id: rstcheck
      #   name: rstcheck
      #   entry: rstcheck
      #   language: system
      #   files: README.rst
      #   stages: [commit]
      #   require_serial: true

      - id: must-have-signoff
        name: must-have-signoff
        entry: 'grep "Signed-off-by:"'
        language: system
        stages: [prepare-commit-msg]
        require_serial: true
