name: Test

on:
  workflow_call:

permissions:
  contents: read

jobs:
  go:
    name: Test Go
    strategy:
      matrix:
        runner: [macos-latest, ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.runner }}
    steps:
      - uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.23"
          check-latest: true
          cache: false
      - name: Install mage
        run: go install github.com/magefile/mage@v1.15.0
      - name: Run unit tests
        run: mage test:unit

  python:
    name: Test Python
    strategy:
      matrix:
        runner: [macos-latest, ubuntu-latest, windows-latest]
        python: ["3.9", "3.10", "3.11", "3.12"]
    runs-on: ${{ matrix.runner }}
    steps:
      - uses: actions/checkout@v4
      - name: Install uv
        uses: astral-sh/setup-uv@v3
      - name: Set up Python ${{ matrix.python }}
        run: uv python install ${{ matrix.python }}
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.23"
          check-latest: true
          cache: false
      - name: Install mage
        run: go install github.com/magefile/mage@v1.15.0
      - name: Initialize MLflow repo
        run: mage repo:init
      - name: Create virtual environment
        run: uv venv --python ${{ matrix.python }}
      - name: Install our package in editable mode
        run: uv sync --all-extras
      - name: Run integration tests
        run: mage test:python
        continue-on-error: ${{ matrix.runner == 'macos-latest' }}
